// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tianyan.proto

package tianyan

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chat struct {
	Mid                  *int64    `protobuf:"varint,1,opt,name=mid" json:"mid,omitempty"`
	Channel              *int32    `protobuf:"varint,2,req,name=channel,def=77" json:"channel,omitempty"`
	Frome                *ChatUser `protobuf:"bytes,3,req,name=frome" json:"frome,omitempty"`
	To                   *ChatUser `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
	Content              *string   `protobuf:"bytes,5,req,name=content" json:"content,omitempty"`
	ZoneId               *int32    `protobuf:"varint,6,req,name=zone_id,def=77" json:"zone_id,omitempty"`
	ZoneName             *string   `protobuf:"bytes,7,req,name=zone_name" json:"zone_name,omitempty"`
	Ip                   *string   `protobuf:"bytes,8,req,name=ip" json:"ip,omitempty"`
	Banned               *int32    `protobuf:"varint,9,opt,name=banned,def=77" json:"banned,omitempty"`
	Extra                *string   `protobuf:"bytes,10,opt,name=extra" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_34f826c290f294d7, []int{0}
}

func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (m *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(m, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

const Default_Chat_Channel int32 = 77
const Default_Chat_ZoneId int32 = 77
const Default_Chat_Banned int32 = 77

func (m *Chat) GetMid() int64 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

func (m *Chat) GetChannel() int32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return Default_Chat_Channel
}

func (m *Chat) GetFrome() *ChatUser {
	if m != nil {
		return m.Frome
	}
	return nil
}

func (m *Chat) GetTo() *ChatUser {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Chat) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Chat) GetZoneId() int32 {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return Default_Chat_ZoneId
}

func (m *Chat) GetZoneName() string {
	if m != nil && m.ZoneName != nil {
		return *m.ZoneName
	}
	return ""
}

func (m *Chat) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Chat) GetBanned() int32 {
	if m != nil && m.Banned != nil {
		return *m.Banned
	}
	return Default_Chat_Banned
}

func (m *Chat) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type ChatUser struct {
	PlayerId             *int64   `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	UserId               *int64   `protobuf:"varint,2,req,name=user_id" json:"user_id,omitempty"`
	Nickname             *string  `protobuf:"bytes,3,req,name=nickname" json:"nickname,omitempty"`
	Level                *int32   `protobuf:"varint,4,req,name=level,def=77" json:"level,omitempty"`
	VipLevel             *int32   `protobuf:"varint,5,opt,name=vip_level,def=77" json:"vip_level,omitempty"`
	Power                *int64   `protobuf:"varint,6,opt,name=power" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatUser) Reset()         { *m = ChatUser{} }
func (m *ChatUser) String() string { return proto.CompactTextString(m) }
func (*ChatUser) ProtoMessage()    {}
func (*ChatUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_34f826c290f294d7, []int{1}
}

func (m *ChatUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatUser.Unmarshal(m, b)
}
func (m *ChatUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatUser.Marshal(b, m, deterministic)
}
func (m *ChatUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatUser.Merge(m, src)
}
func (m *ChatUser) XXX_Size() int {
	return xxx_messageInfo_ChatUser.Size(m)
}
func (m *ChatUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatUser.DiscardUnknown(m)
}

var xxx_messageInfo_ChatUser proto.InternalMessageInfo

const Default_ChatUser_Level int32 = 77
const Default_ChatUser_VipLevel int32 = 77

func (m *ChatUser) GetPlayerId() int64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *ChatUser) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ChatUser) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *ChatUser) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return Default_ChatUser_Level
}

func (m *ChatUser) GetVipLevel() int32 {
	if m != nil && m.VipLevel != nil {
		return *m.VipLevel
	}
	return Default_ChatUser_VipLevel
}

func (m *ChatUser) GetPower() int64 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func init() {
	proto.RegisterType((*Chat)(nil), "tianyan.Chat")
	proto.RegisterType((*ChatUser)(nil), "tianyan.ChatUser")
}

func init() { proto.RegisterFile("tianyan.proto", fileDescriptor_34f826c290f294d7) }

var fileDescriptor_34f826c290f294d7 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x6e, 0xeb, 0x20,
	0x14, 0x86, 0x05, 0x0e, 0xb1, 0x39, 0x51, 0x74, 0xaf, 0xa9, 0x2a, 0x9d, 0xa5, 0x12, 0xca, 0xc4,
	0x94, 0xa1, 0x4b, 0xa4, 0xae, 0x7d, 0x86, 0xce, 0x16, 0xb5, 0x4f, 0x15, 0x54, 0x1b, 0x2c, 0x42,
	0xd3, 0xba, 0x6f, 0xd9, 0x37, 0xaa, 0x4c, 0x52, 0xab, 0x43, 0x37, 0xf8, 0xe0, 0xe7, 0xfb, 0x39,
	0xb0, 0x4d, 0xce, 0xfa, 0xc9, 0xfa, 0xfd, 0x18, 0x43, 0x0a, 0xaa, 0xbc, 0x6e, 0x77, 0x5f, 0x0c,
	0x56, 0x8f, 0x47, 0x9b, 0xd4, 0x06, 0x8a, 0xc1, 0x75, 0xc8, 0x34, 0x33, 0x85, 0xba, 0x81, 0xb2,
	0x3d, 0x5a, 0xef, 0xa9, 0x47, 0xae, 0xb9, 0x11, 0x0f, 0xfc, 0x70, 0x50, 0x1a, 0xc4, 0x4b, 0x0c,
	0x03, 0x61, 0xa1, 0xb9, 0xd9, 0xdc, 0xd7, 0xfb, 0x9f, 0x27, 0xe7, 0xfc, 0xd3, 0x89, 0xa2, 0xba,
	0x03, 0x9e, 0x02, 0xae, 0x34, 0xfb, 0xfb, 0xf8, 0x1f, 0x94, 0x6d, 0xf0, 0x89, 0x7c, 0x42, 0xa1,
	0xb9, 0x91, 0xb3, 0xe6, 0x33, 0x78, 0x6a, 0x5c, 0x87, 0xeb, 0x45, 0x53, 0x83, 0xcc, 0xd0, 0xdb,
	0x81, 0xb0, 0xcc, 0xf7, 0x00, 0xb8, 0x1b, 0xb1, 0xca, 0x6b, 0x05, 0xeb, 0xe7, 0xb9, 0x59, 0x87,
	0x52, 0xb3, 0x6b, 0x64, 0x0b, 0x82, 0x3e, 0x52, 0xb4, 0x08, 0x9a, 0x19, 0xb9, 0x9b, 0xa0, 0x5a,
	0x9c, 0x35, 0xc8, 0xb1, 0xb7, 0x13, 0xc5, 0x26, 0x7f, 0x8e, 0x9b, 0x62, 0xae, 0xf1, 0x76, 0xba,
	0x00, 0x9e, 0xc1, 0x7f, 0xa8, 0xbc, 0x6b, 0x5f, 0xb3, 0xb0, 0xc8, 0x92, 0x1a, 0x44, 0x4f, 0x67,
	0xea, 0x71, 0xb5, 0xd4, 0xba, 0x05, 0x79, 0x76, 0x63, 0x73, 0xc1, 0xe2, 0xb7, 0x7a, 0x0c, 0xef,
	0x14, 0x71, 0x3d, 0x0f, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x25, 0x61, 0xca, 0x41, 0x67, 0x01,
	0x00, 0x00,
}
